### ISSUE TITLE
Where to get more documents about Styx？

### ISSUE THREAD

**Issue by tianyayoucao** [streaming-analytics/Styx#1]
There seems no enough documents about this project，more explanations would be helpful.

**Comment by geerdink** [comment]
Hi Tian, please check the Readme file and the folder presentations. The presentations are actually reveal.js slides, see for example https://streaming-analytics.github.io/Styx/presentations/styx.html#/.
Also see these videos: https://www.youtube.com/watch?v=lfRDNW40rqY and https://www.youtube.com/watch?v=A2nQzSfZ3fE
Please let me know if you want more information!
